import { Seller, Product, Category } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat1', name: 'All', emoji: '✨', productCount: 45 },
  { id: 'cat2', name: 'Keychains', emoji: '🔑', productCount: 12 },
  { id: 'cat3', name: 'Thrift', emoji: '👕', productCount: 8 },
  { id: 'cat4', name: 'Custom', emoji: '🎨', productCount: 15 },
  { id: 'cat5', name: 'Accessories', emoji: '💍', productCount: 10 },
];

export const MOCK_SELLERS: Seller[] = [
  {
    id: 's1',
    username: 'keychainph',
    displayName: 'Keychain PH by Charl Dul',
    avatarUrl: 'https://picsum.photos/seed/charl-avatar/200',
    bio: 'Sanrio, anime, custom keychains! Shipping nationwide from QC.',
    messengerUrl: 'https://m.me/keychainph',
    whatsappNum: '639171234567',
    trustScore: 88,
    trustTier: 'elite',
    idVerified: true,
    tradesCount: 142,
    createdAt: '2022-03-15',
    primaryColor: '#7B6FE8',
  },
  {
    id: 's2',
    username: 'thrifthubmnl',
    displayName: 'ThriftHub Manila',
    avatarUrl: 'https://picsum.photos/seed/thrift-shop/200',
    bio: 'Y2K thrift, vintage finds, pre-loved. Weekly drops!',
    messengerUrl: 'https://m.me/thrifthubmnl',
    whatsappNum: null,
    trustScore: 62,
    trustTier: 'verified',
    idVerified: true,
    tradesCount: 37,
    createdAt: '2023-01-08',
    primaryColor: '#1DB97A',
  },
  {
    id: 's3',
    username: 'artisan.jen',
    displayName: 'Artisan Jen',
    avatarUrl: 'https://picsum.photos/seed/artisan-girl/200',
    bio: 'Handmade clay charms and personalized jewelry.',
    messengerUrl: 'https://m.me/artisanjen',
    whatsappNum: '639189876543',
    trustScore: 45,
    trustTier: 'rising',
    idVerified: false,
    tradesCount: 12,
    createdAt: '2024-05-20',
    primaryColor: '#E86FAA',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    sellerId: 's1',
    categoryId: 'cat2',
    title: 'Sanrio Keychain Set (5pcs)',
    description: 'Cute pastel Sanrio characters. BPA-free acrylic. Perfect for bags!',
    price: 129,
    images: ['https://images.unsplash.com/photo-1606103836294-03221932339d?q=80&w=800&auto=format&fit=crop'],
    stockQty: 8,
    status: 'available',
    isFeatured: true,
    viewCount: 340,
    createdAt: '2024-11-01',
  },
  {
    id: 'p2',
    sellerId: 's1',
    categoryId: 'cat2',
    title: 'Hello Kitty Mini Charm',
    description: 'Limited edition HK charm. Fits most phone cases and bags.',
    price: 89,
    images: ['https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?q=80&w=800&auto=format&fit=crop'],
    stockQty: 2,
    status: 'low',
    isFeatured: false,
    viewCount: 210,
    createdAt: '2024-11-05',
  },
  {
    id: 'p3',
    sellerId: 's2',
    categoryId: 'cat3',
    title: 'Y2K Denim Cargo Jacket — M',
    description: 'Authentic Y2K vibes, great condition. Oversized fit.',
    price: 320,
    images: ['https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?q=80&w=800&auto=format&fit=crop'],
    stockQty: 0,
    status: 'sold_out',
    isFeatured: true,
    viewCount: 185,
    createdAt: '2024-10-28',
  },
  {
    id: 'p4',
    sellerId: 's3',
    categoryId: 'cat4',
    title: 'Custom Clay Bag Tag',
    description: 'Personalized with your name. Choose your colors!',
    price: 150,
    images: ['https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=800&auto=format&fit=crop'],
    stockQty: 15,
    status: 'available',
    isFeatured: false,
    viewCount: 95,
    createdAt: '2024-11-10',
  },
  {
    id: 'p5',
    sellerId: 's1',
    categoryId: 'cat2',
    title: 'Cinnamoroll Plushie Clip',
    description: 'Soft cinnamoroll clip for your backpack.',
    price: 199,
    images: ['https://images.unsplash.com/photo-1559563458-527298cb2B42?q=80&w=800&auto=format&fit=crop'],
    stockQty: 5,
    status: 'available',
    isFeatured: false,
    viewCount: 420,
    createdAt: '2024-11-12',
  },
  {
    id: 'p6',
    sellerId: 's2',
    categoryId: 'cat3',
    title: 'Vintage Band Tee (Nirvana)',
    description: 'Distressed look, size L. One of a kind finds.',
    price: 450,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800&auto=format&fit=crop'],
    stockQty: 1,
    status: 'low',
    isFeatured: true,
    viewCount: 560,
    createdAt: '2024-11-13',
  },
];
